"""added city to user

Revision ID: 931410f2faa5
Revises: 3e7528386f27
Create Date: 2021-01-21 10:37:33.172683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931410f2faa5'
down_revision = '3e7528386f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
